export const apiPaths = {
  products: '/api/products',
  productDetail: '/api/products/:productId',
  productCategory: '/api/products/category/:categoryId',
  productVariants: '/api/products/:productId/variants',
  productVariant: '/api/products/:productId/variants/:variantId',
  categories: '/api/categories',
  cart: '/api/cart',
  cartItems: '/api/cart/items',
  cartItem: '/api/cart/items/:itemId',
  orders: '/api/orders',
  orderBuy: '/api/orders/buy',
  orderById: '/api/orders/:orderId',
  orderStatus: '/api/orders/:orderId/status',
  comments: '/api/comments',
  commentReact: '/api/comments/:commentId/react',
  commentDelete: '/api/comments/:commentId',
  authRegister: '/api/users/register',
  authLogin: '/api/users/login',
  authMe: '/api/users/me',
}
